### ISSUE TITLE
Unicode problem on MacOS

### ISSUE THREAD

**Issue by marcodelmastro** [wiso/ListOfPublicationsFromInspireHEP#1]
Programs seems to work fine, but when dumping query results to file I get a unicode-related error:

Traceback (most recent call last):
  File "./create_bibtex.py", line 56, in <module>
    if content.count('@') == 0:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2597: ordinal not in range(128)

Using this test query (or other similar ones):

./create_bibtex.py --query author%3AR.Turra.1+AND+collection%3Apublished+AND+date%3A2011

For the record, I'm running on macOS with python 2.7.13, with:

LANG=C
LC_ALL=en_US.utf8

Nothing urgent! Ciao, M.

**Comment by wiso** [comment]
I have tried all the python version I have access 2.6, 2.7 (up to 2.7.12), on fedora, sl6 and on a mac. I can't reproduce the issue.

I have done a small change, please retry the master branch

**Comment by marcodelmastro** [comment]
Thanks for looking into this, it was actually a bug in my configuration, adding:

export LC_ALL=en_US.UTF-8

(with the proper spelling!) solved the issue.

M.
